version: '3.7'
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: on-failure
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
    - /data/db